name: Generate Snake
on:
  # Schedule updates (every day)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          gif_out_path: ./github-contribution-grid-snake.gif
          svg_out_path: ./github-contribution-grid-snake.svg

      - name: Push to GitHub
        uses: EndBug/add-and-commit@main
        with:
          branch: main
          message: 'Generate Contribution Snake'
